### ISSUE TITLE
too large text (follow/unfollow)

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [myleneb/theme_nin#19]
- see pics below
- OK: in the "who to follow" section the size is ok
- OK: twister-html doesn't show this large text anomaly

firefox 40.0
![bildschirmfoto vom 2015-09-13 16 49 16](https://cloud.githubusercontent.com/assets/642286/9837261/baec7608-5a39-11e5-803f-f1b396cca304.png)

qupzilla
![qupzilla_bildschirmfoto vom 2015-09-13 16 51 51](https://cloud.githubusercontent.com/assets/642286/9837262/c20b5e86-5a39-11e5-8c0b-17823aa6c121.png)

theme NIN v2, last commit from: Sep 12, 2015

**Comment by myleneb** [comment]
The content of the button was generated with jquery but since one of latest commit on twister-html, it doesn't select the button anymore.
So I replaced 
`$('.userMenu-search-profiles button')` 
by:
`$('li:not(.twister-user) button.follow')`
See https://github.com/myleneb/theme_nin/commit/8df2b657bf82fbaa7fa02254dd06b0ffa95fdd5f 
Fix is not very nice, but works.
